pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'staging',
                    url: 'https://github.com/gitchinmayi/agentic-crypto-tracker.git'
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker compose build'
            }
        }

        stage('Run Containers') {
            steps {
                sh 'docker compose up -d'
            }
        }
    }
}

